export const lang_config = {
  translations: {
    de: {
      zurueck_zu_pfad: "Zurück zu Pfad",
      vorlesen: "Vorlesen",
      text_groesser_kleiner: "Text größer/kleiner",
      kopiert: "linkt gespeichert!",
      teilen: "Teilen",
      drucken: "Drucken",
      einklappen: "Alles einklappen",
      ausklappen: "Alles ausklappen",
      pfade: "Erzählstrang",
      ansicht: "Ansicht",
      local: "Locale Sicht",
      filter: "Inhalte filtern",
      keine_filter: "Keine Filtermöglichkeit",
      anwenden: "Anwenden",
      aktiver_strang: "Aktiver Erzählstrang",
    },
    en: {
      zurueck_zu_pfad: "Back to path",
      vorlesen: "Read aloud",
      text_groesser_kleiner: "Text larger/smaller",
      kopiert: "Saved to clipboard!",
      teilen: "Share",
      drucken: "Print",
      einklappen: "Collapse all",
      ausklappen: "Expand all",
      pfade: "Narrative thread",
      ansicht: "View",
      local: "Local view",
      filter: "Filter content",
      keine_filter: "No filter option",
      anwenden: "Apply",
      aktiver_strang: "Active narrative thread",
    },
  },
};
